### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by ww9000** [CS2103JAN2017-W10-B3/main#5]
- Include image of the UI (upload as doc/images/Ui.png)
- Write a short description
- Link to User Guide, Developer Guide, Learning Outcomes, About Us, Contact Us
- Include acknowledgements (Also, remember to acknowledge the original source of the code i.e. The sample project created by SE-EDU initiative at https://github.com/se-edu/)

**Comment by yinatoh** [comment]
done!
