### ISSUE TITLE
Include Collate BY FRIDAY

### ISSUE THREAD

**Issue by chenpenghao** [CS2103JAN2017-W10-B3/main#59]

**Comment by hwkchia** [comment]
Appreciate if this can be done as soon as possible?

**Comment by ww9000** [comment]
Yes we did this actually but the .md files in the collated file returned errors that failed our Travis so removed it again.

The error is something like '\r\n should be replaced with \n'.

But I'll just upload it again in a branch in a minute.

**Comment by ww9000** [comment]
Done: [https://github.com/CS2103JAN2017-W10-B3/main/tree/CollatedFolder](url)

**Comment by hwkchia** [comment]
Ok, I will review from the CollatedFolder Branch.  Please see to it that the collated folder appears on the master branch.  Our scripts will pull the collated files from the master branch.
